server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.5.17:3306/admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

